### ISSUE TITLE
Unable to use built-in libraries from IDE 1.6.7

### ISSUE THREAD

**Issue by thomas-alrek** [jaquesclaudino/arduino-netbeans#1]
I was unable to include libraries from $(ARDUINO_BASE_DIR)/hardware/arduino/avr/libraries/
Even if I have also set the path in "Code Assistance", for both "C Compiler" and "C++ Compiler", it still won't work.
NetBeans is correctly autocompleting the #define statement, but when I try to compile it, I get "No such file or directory". If I try to include it as an absolute path, I get the following error: 

```
avr-gcc -o dist/Debug/Arduino-Windows/debug build/Debug/Arduino-Windows/main.o  lib/core/arduinocore.a lib/libs/arduinolibs.a -Os -Wl,--gc-sections,--relax -mmcu=atmega328p -lm     build/Debug/Arduino-Windows/main.o: In function `__static_initialization_and_destruction_0': 
C:\path\to/main.cpp:5: undefined reference to `SoftwareSerial::SoftwareSerial(unsigned char, unsigned char, bool)'
C:\path\to/main.cpp:5: undefined reference to `SoftwareSerial::~SoftwareSerial()'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [dist/Debug/Arduino-Windows/debug.exe] Error 1
make[2]: Leaving directory `C:/path/to'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory `C:/path/to'
make: *** [.build-impl] Error 2
```

I have also tried to uncomment the line in the MAKEFILE (INCLUDE_LIBS=SoftwareSerial).

However, if I copy or move the libraries from $(ARDUINO_BASE_DIR)/hardware/arduino/avr/libraries/ to $(ARDUINO_BASE_DIR)/libraries/, I am able to include and compile successfully.

**Comment by jaquesclaudino** [comment]
Currently, your solution is correct. This is because in arduino 1.0 all the libraries was in $(ARDUINO_BASE_DIR)/libraries.
I'll looking to fix that in newer versions of the plugin.

**Comment by jaquesclaudino** [comment]
Also, another workaround is add the path in the Makefile variable;

INCLUDE_LIBS=Firmata;../hardware/arduino/avr/libraries/SoftwareSerial;

**Comment by thomas-alrek** [comment]
Great, thanks for the tip. And thank you for an excellent plugin

**Comment by jaquesclaudino** [comment]
Version 2.0.1: Added improvements in project creation wizard to help this issue
