### ISSUE TITLE
cant execute

### ISSUE THREAD

**Issue by namila007** [jaquesclaudino/arduino-netbeans#3]
hi i did everything as said in the readme file.when i compile a code i get following error 
`cd 'C:\Users\namil\Documents\NetBeansProjects\Arduino'
cmd.exe /c rm -rf build/Debug/Arduino1-Windows/main.o
'"rm"' is not recognized as an internal or external command,
operable program or batch file.`

i even setup the variable paths and in makefile paths
http://imgur.com/atWXEu0

**Comment by namila007** [comment]
`cd 'C:\Users\namil\Documents\NetBeansProjects\Arduino'
C:\Program1\GnuWin32\bin\make.exe -f Makefile CONF=Debug
'test' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
mkdir -p lib/core/
The syntax of the command is incorrect.
make: *** [lib/core/abi.cpp.o] Error 1`

this is what i get when i build n run

**Comment by jaquesclaudino** [comment]
Hi,

  You can install cygwin to fix that. The 'test' is an unix tool used in
the make process.

Best regards

Em 29/07/2016 09:16, "Namila Bandara" notifications@github.com escreveu:

**Comment by namila007** [comment]
it worked.thank you for helping :+1: :)

**Comment by namila007** [comment]
there is a new issue ,when compile n run it says missing libusb0.dll 
`C:/Program1/Arduino/hardware/tools/avr/bin/avrdude -C C:/Program1/Arduino/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P COM3 -b115200 -D -Uflash:w:dist/Debug/Arduino1-Windows/arduino.hex:i
make: *** [upload] Error -1073741515
RUN FAILED (exit value 2, total time: 2s)`

, i tried dl and paste that dll in to sys and it didnt work, i found this https://github.com/libusb/libusb ,how to use it :/

ps:im using win10

**Comment by namila007** [comment]
ok everything worked after dl dll from > [libusb0dll](http://www.dlldump.com/download-dll-files_new.php/dllfiles/L/libusb0.dll/200511208/download.html) and move it to `C:\Windows\SysWOW64` and libusb0.sys to system32/drivers :)
